"""Initial migration

Revision ID: 4cfee3dae7c2
Revises: 
Create Date: 2026-03-12 13:01:13.375626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cfee3dae7c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('firebase_uid', sa.String(
                        length=128), nullable=False),
                    sa.Column('display_name', sa.String(
                        length=100), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=True),
                    sa.Column('phone', sa.String(length=20), nullable=True),
                    sa.Column('bio', sa.String(length=500), nullable=True),
                    sa.Column('date_of_birth', sa.Date(), nullable=True),
                    sa.Column('gender', sa.String(length=20), nullable=True),
                    sa.Column('looking_for', sa.String(
                        length=20), nullable=True),
                    sa.Column('discovery_radius_km',
                              sa.Integer(), nullable=True),
                    sa.Column('age_min', sa.Integer(), nullable=True),
                    sa.Column('age_max', sa.Integer(), nullable=True),
                    sa.Column('latitude', sa.Float(), nullable=True),
                    sa.Column('longitude', sa.Float(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('is_verified', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('last_active_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), [
                              'email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_firebase_uid'), [
                              'firebase_uid'], unique=True)
        batch_op.create_index('ix_users_gender', ['gender'], unique=False)
        batch_op.create_index('ix_users_is_active', [
                              'is_active'], unique=False)
        batch_op.create_index('ix_users_location', [
                              'latitude', 'longitude'], unique=False)

    op.create_table('blocks',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('blocker_id', sa.UUID(), nullable=False),
                    sa.Column('blocked_id', sa.UUID(), nullable=False),
                    sa.Column('reason', sa.String(length=255), nullable=True),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['blocked_id'], ['users.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['blocker_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint(
                        'blocker_id', 'blocked_id', name='uq_block_pair')
                    )
    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.create_index('ix_blocks_blocked', [
                              'blocked_id'], unique=False)
        batch_op.create_index('ix_blocks_blocker', [
                              'blocker_id'], unique=False)

    op.create_table('matches',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user1_id', sa.UUID(), nullable=False),
                    sa.Column('user2_id', sa.UUID(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('matched_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user1_id'], ['users.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['user2_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint(
                        'user1_id', 'user2_id', name='uq_match_pair')
                    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index('ix_matches_is_active', [
                              'is_active'], unique=False)
        batch_op.create_index('ix_matches_user1', ['user1_id'], unique=False)
        batch_op.create_index('ix_matches_user2', ['user2_id'], unique=False)

    op.create_table('swipes',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('swiper_id', sa.UUID(), nullable=False),
                    sa.Column('target_user_id', sa.UUID(), nullable=False),
                    sa.Column('direction', sa.String(
                        length=20), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['swiper_id'], ['users.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['target_user_id'], [
                        'users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('swiper_id', 'target_user_id',
                                        name='uq_swipe_pair')
                    )
    with op.batch_alter_table('swipes', schema=None) as batch_op:
        batch_op.create_index('ix_swipes_direction', [
                              'direction'], unique=False)
        batch_op.create_index('ix_swipes_swiper', ['swiper_id'], unique=False)
        batch_op.create_index('ix_swipes_target', [
                              'target_user_id'], unique=False)

    op.create_table('user_photos',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('url', sa.String(length=512), nullable=False),
                    sa.Column('position', sa.Integer(), nullable=False),
                    sa.Column('is_primary', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('user_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_photos_user_id'), [
                              'user_id'], unique=False)
        batch_op.create_index('ix_user_photos_user_position', [
                              'user_id', 'position'], unique=False)

    op.create_table('messages',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('match_id', sa.UUID(), nullable=False),
                    sa.Column('sender_id', sa.UUID(), nullable=False),
                    sa.Column('body', sa.Text(), nullable=False),
                    sa.Column('message_type', sa.String(
                        length=20), nullable=False),
                    sa.Column('is_read', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['match_id'], ['matches.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['sender_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('ix_messages_is_read', [
                              'match_id', 'is_read'], unique=False)
        batch_op.create_index('ix_messages_match_created', [
                              'match_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_match_id'), [
                              'match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_sender_id'), [
                              'sender_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_messages_match_id'))
        batch_op.drop_index('ix_messages_match_created')
        batch_op.drop_index('ix_messages_is_read')

    op.drop_table('messages')
    with op.batch_alter_table('user_photos', schema=None) as batch_op:
        batch_op.drop_index('ix_user_photos_user_position')
        batch_op.drop_index(batch_op.f('ix_user_photos_user_id'))

    op.drop_table('user_photos')
    with op.batch_alter_table('swipes', schema=None) as batch_op:
        batch_op.drop_index('ix_swipes_target')
        batch_op.drop_index('ix_swipes_swiper')
        batch_op.drop_index('ix_swipes_direction')

    op.drop_table('swipes')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index('ix_matches_user2')
        batch_op.drop_index('ix_matches_user1')
        batch_op.drop_index('ix_matches_is_active')

    op.drop_table('matches')
    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.drop_index('ix_blocks_blocker')
        batch_op.drop_index('ix_blocks_blocked')

    op.drop_table('blocks')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_location')
        batch_op.drop_index('ix_users_is_active')
        batch_op.drop_index('ix_users_gender')
        batch_op.drop_index(batch_op.f('ix_users_firebase_uid'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
